[package]
name = "odoh-client-rs"
version = "1.0.0"
authors = [ "Tanya Verma <tverma@cloudflare.com>" ]
edition = "2018"
license = "BSD-2-Clause"
description = "Rust client for Oblivious DNS over HTTPS (ODoH) protocol version 1"
repository = "https://github.com/cloudflare/odoh-client-rs/"
keywords = [ "odoh", "protocols", "dns", "doh", "privacy" ]
categories = [ "network-programming", "cryptography" ]

[dependencies]
anyhow = "1"
bytes = "1.2"
clap = "2.33"
env_logger = "0.8"
futures = "0.3"
hex = "0.4"
lazy_static = "1.4"
log = "0.4"
odoh-rs = "=1.0.0-alpha.1"
rand = { version = "0.8", features = [ "std_rng" ], default-features = false }
regex = "1"
reqwest = { version = "0.11", features = [ "cookies" ] }
serde = { version = "1.0", features = [ "derive" ] }
tokio = { version = "1", features = [ "full" ] }
toml = "0.5"
trust-dns-client = "0.20.1"
trust-dns-proto = "0.20.1"
url = "2.2"

[dev-dependencies]
assert_cmd = "1"
